### ISSUE TITLE
[1.19] Cant join vanilla servers.

### ISSUE THREAD

**Issue by Pokihead** [Darkhax-Minecraft/Bookshelf#186]
Hey,
with bookshelf 14.02 for MC 1.19 i cant join my server anymore, without it it works just fine.
Iam using forge 41.0.22 and no other mod for testing purposes so it must be this mod.
Normally i would use bookshelf for EnchantmentDescriptionMod.

Here a picture of the error:
![MC_Error_Bookshelf](https://user-images.githubusercontent.com/37344330/173789764-de9748e4-5db1-4d29-a54d-e141e46e367f.jpg)

here is the latest log:
https://pastebin.com/T6dmtjvB

Update this error is still in Bookshelf 14.03

**Comment by Darkhax** [comment]
Hello, can you please repost the log file? It's saying it was deleted by the author.

**Comment by Pokihead** [comment]
Strange, but here it is:
[latest2.log](https://github.com/Darkhax-Minecraft/Bookshelf/files/8908246/latest2.log)
and the debug.log
[debug.log](https://github.com/Darkhax-Minecraft/Bookshelf/files/8908267/debug.log)

**Comment by Darkhax** [comment]
I am not able to reproduce this issue using a Forge client and Forge server with the same version of Bookshelf. Is the server you are connecting to vanilla?

**Comment by Pokihead** [comment]
The server is a forge server too same Version as client.
Maybe it is fixed by forge already? Which forge version you are using?

**Comment by Darkhax** [comment]
I am using Forge 41.0.27. It's worth trying an update, although I don't see anything obvious in their changelog related to this.

**Comment by Pokihead** [comment]
I tried again with 41.0.30 but same error.
Do Bookshelf need to be installed on server too now?
Dont know what could be causing it only thing i found is that since 1.13 or 1.14 there is something with big and small letters which could be an issue.
on client it is the only installed mod, on server there is only dynmap and deathcounter both for 1.19

**Comment by Darkhax** [comment]
Yes Bookshelf should be installed on both the client and server, although having it installed client-side only should not be causing this issue.

**Comment by Pokihead** [comment]
ok then i will try installing it to server.
For me it is only important that complete vanilla clients can join too

**Comment by Pokihead** [comment]
news:
1. if i install it on the server it works and i can connect if i have it also on client
2. if i have forge client without it it says i need it for connect
3. vanilla clients can connect without it

it would be better if no client would need to have it because i only use it for client only mods. Dont know if that is possible or intended

**Comment by Pokihead** [comment]
Can you or better do you want to address the issue that it has to be on server and client? Like it was in 1.18
If not it is ok, just want to know and i think then this issue can be closed.

**Comment by Darkhax** [comment]
You're right, ideally the server would not need Bookshelf installed. Everything should be working fine, however it looks like Minecraft changed something in the 1.19 network protocol. This needs more testing to narrow down what's going wrong, and it may be a Forge bug. I am leaving this issue open while this is being looked into.

**Comment by Darkhax** [comment]
It looks like Forge has since fixed this issue. I am testing now and a Forge+Bookshelf client can connect to a vanilla server, and a vanilla client can connect to a Forge+Bookshelf server.

- Minecraft 1.19
- Forge 41.1.0
- Bookshelf 14.2.10.

**Comment by Pokihead** [comment]
Just tested it:

- Server MC 1.19 with Forge 41.1.0 and Dynmap
- Client MC 1.19 with Forge 41.1.0 and Bookshelf 14.2.10

and i still get the same error as before :/
it only works if server has Bookshelf too, but then a Forge Client without it can't connect.

**Comment by Pokihead** [comment]
As an update with MC 1.19.2, Forge 43.1.3 and bookshelf-1.19.2-16.1.4 everything works fine again.
So this thread can be closed.
thanks :)
