### ISSUE TITLE
Error at world creation

### ISSUE THREAD

**Issue by SH4DOW4RE** [Darkhax-Minecraft/Bookshelf#211]
When I try to create a world with a custom modpack in 1.18.2 Forge using the latest version of Bookshelf for a couple of mods, I get an error with the mods datapacks. Inside the debug.log I could see that it was Bookshelf trowing an error.

Is that a known issue ?

**Comment by Darkhax** [comment]
There are no known issues with Bookshelf. Please include your crash log so I can see what's going wrong.

**Comment by SH4DOW4RE** [comment]
[debug.log](https://github.com/Darkhax-Minecraft/Bookshelf/files/11031951/debug.log)
[latest.log](https://github.com/Darkhax-Minecraft/Bookshelf/files/11031952/latest.log)

**Comment by Darkhax** [comment]
Thanks for sharing. It looks like one of the addons for Botany Pots is referencing a block ID that doesn't exist. I've released an update that tries to handle this error in a safer way, please let me know if it works. It may take a minute for CurseForge to register that the file exists. https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/4449847

**Comment by SH4DOW4RE** [comment]
Right now Curseforge doesn't know it exists, but I'll keep you updated when it's available.

**Comment by SH4DOW4RE** [comment]
I still have a problem, but I don't think it's from your mod. Could you still take a look and help me figure it out ?
[crash-2023-03-21_19.54.25-server.txt](https://github.com/Darkhax-Minecraft/Bookshelf/files/11032549/crash-2023-03-21_19.54.25-server.txt)
[debug.log](https://github.com/Darkhax-Minecraft/Bookshelf/files/11032559/debug.log)
[latest.log](https://github.com/Darkhax-Minecraft/Bookshelf/files/11032561/latest.log)

**Comment by Darkhax** [comment]
Based on your new log it looks like the initial issue was caused by invalid recipes in botany_pots_ore_planting. Unfortunately I don't have good answers for your new issue. The stacktrace shows that vanilla code is trying to access vanilla code that doesn't actually exist. This sounds like a core mod that is messing up or potentially a mod for an older version of Minecraft. 

After a closer look, it looks like the code being accessed is something patched in by Forge, so it should exist. Definitely something funky.
